ALTER TYPE "AccountSource" ADD VALUE IF NOT EXISTS 'CLASS_PASS';

ALTER TYPE "LedgerReferenceType" ADD VALUE IF NOT EXISTS 'CLASS_PASS';

ALTER TYPE "LedgerAccount" ADD VALUE IF NOT EXISTS 'ACADEMY_REVENUE';

ALTER TABLE "ClassPass"
ADD COLUMN "priceAtPurchase" DECIMAL(10, 2);
